name: Compile LCD Menu on Arduino

on: [push, pull_request, workflow_dispatch]

jobs:
  compile-arduino:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} /examples/Basic/Basic.ino
