name: Compile LCD Menu on Arduino

on: [push, pull_request, workflow_dispatch]

jobs:
  compile-arduino:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}

      - name: Install Keypad and LCD libraries
        run: |
          arduino-cli lib install Keypad
          arduino-cli lib install LiquidCrystal
          arduino-cli lib install "LiquidCrystal I2C"
          arduino-cli lib install ArduinoJson

      - name: Install LcdMenu Library
        run: mkdir -p /home/runner/Arduino/libraries/LcdMenu/ && cp -r * /home/runner/Arduino/libraries/LcdMenu/

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/Basic
