name: CI Arduino

on: [pull_request, push]

jobs:
  provide-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TMP="["
          for FILE in examples/*/*.ino; do TMP="$TMP\"$FILE\","; done
          TMP="${TMP::-1}]"
          echo "::set-output name=matrix::$TMP"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  compile-arduino:
    needs: provide-examples
    strategy:
      matrix:
        example: ${{ fromJson(needs.provide-examples.outputs.matrix) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Install library dependencies
        run: |
          pio lib install

      - name: Run PlatformIO
        run: pio ci --board=uno
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
