name: Generate Docs

on:
  release:
    types: [created]

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and test Node
        run: npm install
        run: npm test
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Merge changes from master
        run: git merge origin/master

      - name: Add examples to docs
        run: |
          for FILE in examples/*/*.md; do TMP=$FILE; TMP=${TMP//examples\//}; TMP=${TMP//\/README/}; cp $FILE 'docs/examples/'"$TMP"; done
          for FILE in examples/*/*.md; do TMP=$FILE; TMP=${TMP//examples\//}; TMP=${TMP//\/README/}; sed -i '1i---\nlayout: default\ntitle: '"${TMP//.md/}"'\nparent: Examples\n---\n' docs/examples/$TMP; done
          for FILE in docs/examples/*.md; do sed -i 's/\!\[Circuit\](https:\/\/github.com\/forntoh\/LcdMenu\/blob\/gh-pages\/assets\/img\/circuit.png?raw=true)/<img src="{{ site.baseurl }}\/assets\/img\/circuit.png" alt="Circuit">/' $FILE; done

      - name: Embed code into examples
        run: npx embedme docs/examples/*.md

      - name: Generate Ref docs
        run: |
          for FILE in src/*.h; do TMP=$FILE; TMP=${TMP//src\//}; TMP=${TMP//.h/.md}; TMP=${TMP,,}; npx mdcdoc -o docs/ref/$TMP $FILE; done
      
      - name: Add Jekyll headers
        run: |
          for FILE in src/*.h; do TMP=$FILE; TMP=${TMP//src\//}; TMP=${TMP//.h/.md}; TMP=${TMP,,}; sed -i '1i---\nlayout: default\ntitle: '"${FILE//src\//}"'\nparent: Reference\n---\n' docs/ref/$TMP; done

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated docs"

      - name: Push changes
        run: git push
