name: Generate Docs

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get Release Tag
        run: echo "RELEASE_BRANCH=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check Release Tag
        id: check-tag
        run: |
          echo ${RELEASE_BRANCH}
          if [[ ${RELEASE_BRANCH} != *[a-z]* ]]; then
            echo ::set-output name=match::true
          fi

      - name: Set branch to checkout
        if: steps.check-tag.outputs.match == 'true'
        run: echo "RELEASE_BRANCH=master" >> $GITHUB_ENV

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Merge ${{ env.RELEASE_BRANCH }} -> gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git merge origin/${RELEASE_BRANCH} --strategy-option theirs --allow-unrelated-histories

      - name: Add examples to docs
        run: |
          for FILE in examples/*/*.md; do TMP=$FILE; TMP=${TMP//examples\//}; TMP=${TMP//\/README/}; cp $FILE 'docs/examples/'"$TMP"; done
          sleep 2s
          for FILE in examples/*/*.md; do TMP=$FILE; TMP=${TMP//examples\//}; TMP=${TMP//\/README/}; sed -i '1i---\nlayout: default\ntitle: '"${TMP//.md/}"'\nparent: Examples\n---\n' docs/examples/$TMP; done
          sleep 2s
          for FILE in docs/examples/*.md; do sed -i 's/\!\[Circuit\](https:\/\/github.com\/forntoh\/LcdMenu\/blob\/gh-pages\/assets\/img\/circuit.png?raw=true)/<img src="{{ site.baseurl }}\/assets\/img\/circuit.png" alt="Circuit">/' $FILE; done

      - name: Embed code into examples
        run: |
          npx embedme docs/examples/*.md
          sleep 30s

      - name: Generate Ref docs
        run: |
          npm install -g mdcdoc
          for FILE in src/*.h; do TMP=$FILE; TMP=${TMP//src\//}; TMP=${TMP//.h/.md}; TMP=${TMP,,}; mdcdoc -o docs/ref/$TMP $FILE; done
          for FILE in src/*.h; do TMP=$FILE; TMP=${TMP//src\//}; TMP=${TMP//.h/.md}; TMP=${TMP,,}; sed -i '1i---\nlayout: default\ntitle: '"${FILE//src\//}"'\nparent: Reference\n---\n' docs/ref/$TMP; done
          rm -rf debug.log platformio.ini *.txt library.properties CONTRIBUTING.md Gemfile* LICENSE README.md

          git add .
          git commit -m "Generated docs"
          git push
